name: Onboarding

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "create_issue"
        type: choice
        options:
          - create_issue
          - invite_users
      issue_number:
        description: "Issue number to process comments from (required when action is invite_users)"
        required: false
        type: string

permissions: write-all

jobs:
  create_welcome_issue:
    if: ${{ github.event.inputs.action == 'create_issue' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Welcome Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = "Welcome to the GHAS Certification Bootcamp!";
            const issueBody = `
            Welcome to the GHAS Certification Bootcamp! This issue will be a place for you to leave a comment and be invited to join the organization.
            `;
            const { data: issue } = await github.rest.issues.create({
              ...context.repo,
              title: issueTitle,
              body: issueBody,
            });
            core.setOutput("issue_number", issue.number);

  invite_users:
    if: ${{ github.event.inputs.action == 'invite_users' }}
    runs-on: ubuntu-latest
    steps:
      - name: Invite Users
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const issueNumber = context.payload.inputs.issue_number;
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: issueNumber,
            });
            for (const comment of comments) {
              const inviteeId = comment.user.id;
              await github.rest.orgs.createInvitation({
                org: context.repo.owner,
                invitee_id: inviteeId,
                role: "direct_member",
              });
            };
